# Numpy

In [1]:
import numpy as np

Créez à partir d’une liste un array unidimensionnel et vérifiez sa taille et ce qu’il comporte.


In [2]:
arr1=np.array(range(10))
print(arr1.dtype,arr1.shape)

int32 (10,)


Générez des arrays remplis de 0 et de 1 de taille 10.


In [3]:
arr2=np.zeros(10)
arr2.shape

(10,)

In [4]:
arr3=np.ones((10,10))
arr3.shape

(10, 10)

Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array


In [5]:
arr4=np.arange(1,6)
arr4**3

array([  1,   8,  27,  64, 125], dtype=int32)

Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.


In [6]:
arr5=np.arange(start=5,stop=11,dtype=float).reshape(3,2)

np.dot(arr5.T,arr5)

array([[ 155.,  176.],
       [ 176.,  200.]])

Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [7]:
arr6=np.random.randn(1000000)

In [8]:
#on affiche la moyenne, l'écart-type et la médiane
print(np.mean(arr6), arr6.std(), np.median(arr6))

-0.000476231666194 1.00020907215 -0.00158620439874


In [9]:
arr6=np.where(arr6<=0,0,arr6)

In [10]:
np.sort(arr6)

array([ 0.        ,  0.        ,  0.        , ...,  4.50060065,
        4.51865312,  4.64601444])

In [11]:
#on récupère l'index de chaque valeur satisfaisant la condition
np.where(arr6<=4)

(array([     0,      1,      2, ..., 999997, 999998, 999999], dtype=int64),)

In [12]:
arr7=np.arange(6).reshape(2,3)
arr7

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
#on récupère les index à deux dimensions de chaque valeur satisfaisant la condition
np.where(arr7>2)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt

In [14]:
arr8=np.random.randn(10000000).reshape(1000000,10)

In [15]:
np.save("arr8",arr8)

In [16]:
np.savetxt("arr8",arr8)

In [17]:
arr9=np.load("arr8.npy")

In [18]:
arr9.dtype

dtype('float64')

In [19]:
np.savez("arrz9",arr8)

In [20]:
arrz=np.load("arrz9.npz")

arrz.files

['arr_0']

In [21]:
arrz[arrz.files[0]]

array([[ 1.14110147,  0.34019865, -0.63904216, ..., -0.05957653,
        -0.43359311,  0.85287577],
       [ 1.4068182 , -1.0187661 , -0.7050145 , ...,  0.65199638,
         0.15436296,  0.47419943],
       [-1.32177759,  0.57735351,  1.44186503, ..., -0.56670683,
         0.91762156, -0.49764865],
       ..., 
       [ 0.73854853,  0.32493378, -1.95939626, ...,  0.23605613,
        -1.15033615,  1.29314153],
       [ 0.73834274, -0.06624335, -1.53726039, ...,  0.97112348,
        -1.57488111, -0.7014886 ],
       [-1.39682306, -0.55737247,  0.91090402, ..., -0.24484372,
        -0.85293323,  0.84216162]])